name: CI with Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
          key: cache-283a280

      - name: prime-cache-283a280
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
